-- リソースの作成
USE ROLE SYSADMIN;
CREATE OR ALTER DATABASE KITAGAWA_TEST_DB;
CREATE OR ALTER SCHEMA KITAGAWA_TEST_DB.AGENT_PROD;
CREATE OR ALTER SCHEMA KITAGAWA_TEST_DB.AGENT_DEV;
CREATE OR ALTER STAGE KITAGAWA_TEST_DB.AGENT_PROD.AGENT_SPECS;
CREATE OR ALTER WAREHOUSE KITAGAWA_X_SMALL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = '検証用';

-- WIF用サービスユーザーの作成
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE USER KITAGAWA_GHA_DEPLOY_USER
  TYPE = SERVICE
  DEFAULT_ROLE = SYSADMIN
  WORKLOAD_IDENTITY = (
    TYPE = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    SUBJECT = 'repo:cm-kitagawa-zempei@192168639/snowflake-cortex-agents-versioning@1351291095:ref:refs/heads/main'
  );
GRANT ROLE SYSADMIN TO USER KITAGAWA_GHA_DEPLOY_USER;